"""Plan v11 Stage 1 — replay-buffer filter for offline AWAC/IQL/BC bake-off.

Operates on the PER export archives produced by
`PERVanillaStep.export_all()` (see eve_rl/eve_rl/replaybuffer/pervanillastep.py).
Each archive carries `obs_pairs`, `actions`, `rewards`, `terminals`,
`is_demo`, `is_clean`, `episode_returns` (one row per transition), plus the
sum-tree priorities. We discard the sum-tree (priorities are recomputed
from TD errors after load) and emit raw transition arrays the trainer can
concatenate into a fresh buffer.

Plan v11 Stage 1 filtering plan:
- V2 (640k @ 22.2 % target): keep all `is_demo`, keep all `is_clean`,
  stratify failures into 3 return bands (high/mid/low) capped at
  `max_per_failure_stratum` (default 30k) each. The return-band proxy
  replaces the strict terminal-cause split (wfs vs max_steps vs off-path)
  which the buffer doesn't expose — episode_return is the next-best
  partition: high-return failures = "got close, terminal artifact",
  low-return failures = "wandered off early".
- V3 (770k @ 12.4 % target): keep all `is_clean`. Drop saturated
  trajectories by per-transition `max(|action|) < action_abs_max`
  (default 0.85) — prevents re-importing the cath_trans rail collapse.
  V3 does NOT contribute `is_demo` (it's all online rollouts;
  retagging-as-demo is risk audit #9 NO — Stage 5 uses `is_high_value`
  instead).

Designed to be called twice from `DualDeviceNav_offline.py`; the trainer
concatenates the two subsets and pushes them into a single
`PERVanillaStep` of matching capacity. No SOFA / torch deps — pure numpy
so it runs on the host.
"""

import logging
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


# Per-transition arrays the trainer needs. The PER export also has
# `tree`, `position`, `max_priority`, `_sample_count` — those describe
# the sum-tree state of the source buffer and are not transferable, so
# we drop them and the loader re-initializes them at max_priority.
_TRANSITION_FIELDS = (
    "obs_pairs", "actions", "rewards", "terminals",
    "is_demo", "is_clean", "episode_returns",
)


@dataclass
class FilterConfig:
    """Per-source filter knobs. Plan v11 §Stage 1 defaults."""
    keep_is_demo: bool = True
    keep_is_clean: bool = True
    # Failure-stratification (only applied to !is_clean & !is_demo subset).
    stratify_failures: bool = True
    max_per_failure_stratum: int = 30_000
    return_band_edges: tuple = (-5.0, 0.0, 3.0)  # 3 bands: (-inf,-5), [-5,0), [0,3), [3,+inf)
    # Action-magnitude gate (V3 saturation filter).
    action_abs_max: Optional[float] = None  # None disables; V3 uses 0.85
    # Hard cap on output rows (for testing).
    max_rows: Optional[int] = None
    # Source tag carried into the merged buffer (so the trainer can
    # diagnose where each transition came from).
    source_tag: str = ""

    # ---------------------------------------------------------------- #
    # Stage 1B HARD-QUALITY-GATE knobs (Plan v11 §Stage 1B).            #
    # These are STACKED on top of the existing keep-set logic and ONLY  #
    # remove rows; setting them all to defaults reproduces the prior    #
    # behavior exactly.                                                 #
    # ---------------------------------------------------------------- #
    # Drop every is_demo transition unconditionally, regardless of the
    # `keep_is_demo` flag (the V2 demo seeds were generated by a 0-1 %
    # eval-success checkpoint — high noise, low quality).
    drop_all_demos_unconditional: bool = False
    # Episode-return floor; transitions whose `episode_returns >=` this
    # value survive. 0.0 disables (no gate).
    require_episode_return_min: float = 0.0
    # Late-task gate (LocalGuidance arc_past_last_daughter). 0.0 disables.
    # The proxy uses the FLATTENED observation index of the LocalGuidance
    # feature; offsets default to env5's ObsDict layout (see plan_v11 obs
    # schema notes). Threshold is the normalized arclength (0..1) past
    # the last daughter fork.
    late_task_threshold_norm: float = 0.0
    # Flattened observation index of the `arc_past_last_daughter` feature.
    # Gen-4 env5 layout: tracking[0..40), target[40..42), last_action[42..46),
    # guidance[46..97), privileged[97..121). Within the 51-dim guidance the
    # `arc_past_last_daughter` slot is feature index 12 → flat index 58
    # (unchanged by the #5 log-depth channel, which appended at guidance
    # END — indices 46..95 are stable across the 50→51 growth).
    # (The prior comment/value 56 assumed the old last_action=2/guidance=28
    # layout — stale since Gen-3; corrected here for Gen-4 offline archives.
    # Only used by the *_strict offline filters, which must run on
    # Gen-4-format PER archives for this index to be meaningful.)
    late_task_obs_index: int = 58
    # Use first frame of obs_pairs (i.e. obs_pairs[:, 0]) when scoring
    # the late-task gate. obs_pairs is (N, 2, obs_dim) — [0]=s, [1]=s'.
    late_task_use_next_state: bool = False


@dataclass
class FilterResult:
    arrays: dict = field(default_factory=dict)  # _TRANSITION_FIELDS → ndarray
    n_in: int = 0
    n_out: int = 0
    n_demo: int = 0
    n_clean: int = 0
    n_failure: int = 0
    band_counts: tuple = ()
    n_saturated_dropped: int = 0


def load_per_export(path: str) -> dict:
    """Read a `PERVanillaStep.export_all()` archive into a plain dict.
    Trims unused tree/position fields. Returns dict of length-N arrays."""
    data = np.load(path)
    n = int(data["n"])
    out = {}
    for k in _TRANSITION_FIELDS:
        if k not in data.files:
            raise KeyError(
                f"{path} missing field {k!r} — not a PER export archive?"
            )
        out[k] = np.asarray(data[k])[:n]
    return out


def _band(returns: np.ndarray, edges: tuple) -> np.ndarray:
    """Assign each element a band index in 0..len(edges).
    Bands: [-inf, edges[0]), [edges[0], edges[1]), …, [edges[-1], +inf)."""
    band = np.zeros(returns.shape, dtype=np.int32)
    for i, e in enumerate(edges):
        band += (returns >= e).astype(np.int32)
    return band  # ranges 0..len(edges)


def filter_arrays(arrays: dict, cfg: FilterConfig) -> FilterResult:
    """Apply the filter to a loaded PER export. Returns a FilterResult
    whose `arrays` is ready to concat with other sources' results."""
    n = arrays["actions"].shape[0]
    rng = np.random.default_rng(0)

    is_demo = arrays["is_demo"].astype(bool)
    is_clean = arrays["is_clean"].astype(bool)
    actions = arrays["actions"]
    returns = arrays["episode_returns"].astype(np.float64)

    # Saturation drop (V3): any per-transition action exceeds the cap.
    sat_mask = np.zeros(n, dtype=bool)
    if cfg.action_abs_max is not None:
        sat_mask = np.max(np.abs(actions), axis=-1) >= cfg.action_abs_max

    # Start with what we want to keep deterministically.
    keep = np.zeros(n, dtype=bool)
    if cfg.keep_is_demo:
        keep |= is_demo
    if cfg.keep_is_clean:
        keep |= is_clean

    # Failure stratification: transitions outside the keep set so far,
    # which are also not saturated. Sample up to `max_per_failure_stratum`
    # per return band.
    band_counts = []
    if cfg.stratify_failures:
        failure_pool = (~keep) & (~sat_mask)
        bands = _band(returns, cfg.return_band_edges)
        for b in range(len(cfg.return_band_edges) + 1):
            band_mask = failure_pool & (bands == b)
            idx = np.flatnonzero(band_mask)
            if idx.size > cfg.max_per_failure_stratum:
                idx = rng.choice(idx, cfg.max_per_failure_stratum, replace=False)
            band_counts.append(int(idx.size))
            keep[idx] = True

    # Drop saturated transitions even if they got picked above.
    keep &= ~sat_mask

    # ----- Stage 1B HARD-QUALITY-GATE filters ------------------------- #
    # 1. Unconditional demo drop (override any earlier keep_is_demo).
    if cfg.drop_all_demos_unconditional:
        keep &= ~is_demo
    # 2. Episode-return floor.
    if cfg.require_episode_return_min > 0.0:
        keep &= returns >= cfg.require_episode_return_min
    # 3. Late-task LocalGuidance gate.
    if cfg.late_task_threshold_norm > 0.0:
        obs_pairs = arrays.get("obs_pairs", None)
        if obs_pairs is None:
            logger.warning(
                "late_task_threshold_norm set but obs_pairs missing; "
                "skipping late-task gate"
            )
        else:
            # obs_pairs shape: (N, 2, obs_dim). [..., 0, :] = s, [..., 1, :] = s'.
            frame_idx = 1 if cfg.late_task_use_next_state else 0
            try:
                feat = obs_pairs[:, frame_idx, cfg.late_task_obs_index].astype(
                    np.float64
                )
                keep &= feat >= cfg.late_task_threshold_norm
            except (IndexError, ValueError) as exc:
                logger.warning(
                    "Late-task gate failed (obs_pairs shape=%s, idx=%d): %s "
                    "— skipping gate",
                    getattr(obs_pairs, "shape", "?"),
                    cfg.late_task_obs_index,
                    exc,
                )

    if cfg.max_rows is not None and keep.sum() > cfg.max_rows:
        idx = np.flatnonzero(keep)
        idx = rng.choice(idx, cfg.max_rows, replace=False)
        keep = np.zeros(n, dtype=bool)
        keep[idx] = True

    out_arrays = {k: arrays[k][keep] for k in _TRANSITION_FIELDS}

    result = FilterResult(
        arrays=out_arrays,
        n_in=n,
        n_out=int(keep.sum()),
        n_demo=int((is_demo & keep).sum()),
        n_clean=int((is_clean & keep).sum()),
        n_failure=int((keep & ~is_demo & ~is_clean).sum()),
        band_counts=tuple(band_counts),
        n_saturated_dropped=int(sat_mask.sum()),
    )
    logger.info(
        "Filter[%s]: in=%d out=%d (demo=%d clean=%d failure=%d sat_drop=%d bands=%s)",
        cfg.source_tag, result.n_in, result.n_out,
        result.n_demo, result.n_clean, result.n_failure,
        result.n_saturated_dropped, result.band_counts,
    )
    return result


def concat_filtered(results: list) -> dict:
    """Concatenate filter outputs along the transition axis."""
    out = {}
    for k in _TRANSITION_FIELDS:
        out[k] = np.concatenate([r.arrays[k] for r in results], axis=0)
    return out


def _build_cfg(defaults: dict, overrides: dict) -> "FilterConfig":
    """Merge defaults + overrides so caller kwargs replace (not collide
    with) the named-default kwargs in filter_v2 / filter_v3."""
    merged = {**defaults, **overrides}
    return FilterConfig(**merged)


def filter_v2(path: str, **overrides) -> FilterResult:
    cfg = _build_cfg(
        defaults=dict(
            source_tag="V2",
            keep_is_demo=True,
            keep_is_clean=True,
            stratify_failures=True,
            max_per_failure_stratum=30_000,
            action_abs_max=None,
        ),
        overrides=overrides,
    )
    return filter_arrays(load_per_export(path), cfg)


def filter_v3(path: str, **overrides) -> FilterResult:
    cfg = _build_cfg(
        defaults=dict(
            source_tag="V3",
            keep_is_demo=False,  # V3 = online rollouts; no demo tag pollution
            keep_is_clean=True,
            stratify_failures=True,
            max_per_failure_stratum=30_000,
            action_abs_max=0.85,
        ),
        overrides=overrides,
    )
    return filter_arrays(load_per_export(path), cfg)


# ---------------------------------------------------------------------- #
# Stage 1B strict filters — Plan v11 §Stage 1B HARD-QUALITY-GATE.        #
# Both drop ALL failures, drop demo-tag noise, require episode_return>3, #
# and (if obs_pairs flattened to env5's schema) require late-task        #
# arc_past_last_daughter > 0.1.                                          #
# ---------------------------------------------------------------------- #
def filter_v2_strict(path: str, **overrides) -> FilterResult:
    """V2 strict gate (Plan v11 §Stage 1B). Drops demos + failures, keeps
    only clean transitions with episode_return > 3.0 and (optionally) late
    task arc-past-daughter > 0.1."""
    cfg = _build_cfg(
        defaults=dict(
            source_tag="V2_strict",
            keep_is_demo=False,
            keep_is_clean=True,
            stratify_failures=False,
            max_per_failure_stratum=0,
            action_abs_max=None,
            drop_all_demos_unconditional=True,
            require_episode_return_min=3.0,
            late_task_threshold_norm=0.1,
        ),
        overrides=overrides,
    )
    return filter_arrays(load_per_export(path), cfg)


def filter_v3_strict(path: str, **overrides) -> FilterResult:
    """V3 strict gate (Plan v11 §Stage 1B). Drops failures + saturated
    transitions, keeps only clean with episode_return > 3.0 and late-task
    arc-past-daughter > 0.1."""
    cfg = _build_cfg(
        defaults=dict(
            source_tag="V3_strict",
            keep_is_demo=False,
            keep_is_clean=True,
            stratify_failures=False,
            max_per_failure_stratum=0,
            action_abs_max=0.85,
            drop_all_demos_unconditional=True,
            require_episode_return_min=3.0,
            late_task_threshold_norm=0.1,
        ),
        overrides=overrides,
    )
    return filter_arrays(load_per_export(path), cfg)


def compute_diversity_weights(
    arrays: dict,
    *,
    alpha: float = 0.0,
    resolution: float = 0.5,
    max_boost: float = 4.0,
    pool: str = "all",
    dims: Optional[list] = None,
) -> np.ndarray:
    """Stage 1B-v2 — per-transition diversity boost.

    Per the success-diversity workflow (w6ys0odcm): V2/V3 clean episodes
    show an 85/15 split between "fast-push" (avg 83 steps) and
    "slow-pullback" (avg 579 steps) modes (A3 k-means). PC1 explains
    51-62% of action variance (A5). Under `priority_mode=outcome` with
    10x clean boost, the policy mode-collapses onto fast-push and loses
    the slow-pullback expertise needed at certain restore states.

    This function returns a per-transition multiplier `m_i` such that
    final priority becomes `base_priority_i * m_i ** alpha`. m_i is:
        bin_i = floor(actions[i] / resolution).astype(int)
        m_i = sqrt(median(counts) / count[bin_i])
        m_i = clip(m_i, 1/max_boost, max_boost)

    Median normalization keeps mean(m_i) ~ 1 so the global priority
    scale is preserved — only the relative distribution is reshaped.

    Args:
        arrays: filter output dict with `actions` (N, action_dim)
            and `is_clean` (N,) arrays.
        alpha: diversity strength. 0.0 = OFF (return ones).
        resolution: action-grid cell width in normalized [-1, 1] units.
        max_boost: symmetric clamp on the multiplier.
        pool: "all" — count bin occupancy over the full keep-set;
              "clean_only" — count only over is_clean=True transitions
              (sharpens the pullback vs push rebalance).
        dims: list of action-dim indices to use for binning. Default
            None uses [0, 2] (cath_trans + gw_trans — A1/A3 identified
            these as the mode-discriminating dims; gw_rot is near-zero
            so binning on it just adds noise).

    Returns:
        m: (N,) float64 multiplier in [1/max_boost, max_boost].
    """
    n = int(arrays["actions"].shape[0])
    if alpha <= 0.0 or n == 0:
        return np.ones(n, dtype=np.float64)

    actions = np.asarray(arrays["actions"], dtype=np.float64)
    is_clean = np.asarray(arrays["is_clean"], dtype=bool)
    if dims is None:
        dims = [0, 2]  # cath_trans + gw_trans

    # Quantize selected action dims.
    bin_coords = np.floor(actions[:, dims] / float(resolution)).astype(np.int64)
    # Hash each (bin0, bin1, ...) tuple into a single int via a stable
    # row-encoding (uses .view trick that's robust to negative ints).
    # Convert each row of bin_coords to a tuple via structured array.
    bin_keys = np.ascontiguousarray(bin_coords).view(
        [('', bin_coords.dtype)] * bin_coords.shape[1]
    ).ravel()

    # Count bin occupancy over the chosen pool.
    if pool == "clean_only":
        unique_keys, key_inverse = np.unique(bin_keys, return_inverse=True)
        counts_full = np.bincount(key_inverse, weights=is_clean.astype(np.float64))
        counts_full = np.maximum(counts_full, 1.0)
    else:
        unique_keys, key_inverse, counts_full = np.unique(
            bin_keys, return_inverse=True, return_counts=True
        )
    per_transition_count = counts_full[key_inverse].astype(np.float64)
    median_count = float(np.median(counts_full))

    m = np.sqrt(median_count / per_transition_count)
    m = np.clip(m, 1.0 / max_boost, max_boost)
    # Raise to alpha so alpha<1 attenuates the boost, alpha>1 amplifies.
    if alpha != 1.0:
        m = m ** alpha
    # Re-normalize so mean(m)=1 (preserves overall priority mass).
    mean_m = float(m.mean())
    if mean_m > 0:
        m = m / mean_m
    return m


def make_export_dict(
    arrays: dict,
    capacity: int,
    uniform_priority: float = 1.0,
    *,
    diversity_alpha: float = 0.0,
    diversity_resolution: float = 0.5,
    diversity_max_boost: float = 4.0,
    diversity_pool: str = "all",
    diversity_dims: Optional[list] = None,
) -> dict:
    """Plan v11 Stage 1 — wrap filtered transitions into the same dict
    schema `PERVanillaStep.export_all()` produces, so it can be saved
    and loaded by `PERVanillaStepShared.load_buffer_from_file`.

    Pads the per-slot companion arrays (is_demo/is_clean/episode_returns)
    to `capacity`; only the first n slots carry data. Sets every used
    leaf to `uniform_priority` (default 1.0) so PER's first samples are
    effectively uniform — erases the V2-vs-V3 push-order skew (risk
    audit #8) without a separate recompute pass.

    Stage 1B-v2 — when `diversity_alpha > 0`, applies per-transition
    multiplier from `compute_diversity_weights` to the leaf priority.
    Default 0.0 = byte-identical to prior behavior.
    """
    n = int(arrays["actions"].shape[0])
    if n == 0:
        raise ValueError("make_export_dict called with empty arrays")
    if n > capacity:
        raise ValueError(
            f"filtered transitions ({n}) exceed buffer capacity ({capacity})"
        )

    # Companion arrays — pad to capacity with neutral defaults.
    is_demo = np.zeros(capacity, dtype=bool)
    is_clean = np.zeros(capacity, dtype=bool)
    episode_returns = np.zeros(capacity, dtype=np.float64)
    is_demo[:n] = arrays["is_demo"][:n].astype(bool)
    is_clean[:n] = arrays["is_clean"][:n].astype(bool)
    episode_returns[:n] = arrays["episode_returns"][:n].astype(np.float64)

    # Per-leaf priority. Default = uniform; Stage 1B-v2 = uniform * m_i.
    diversity_m = compute_diversity_weights(
        arrays,
        alpha=diversity_alpha,
        resolution=diversity_resolution,
        max_boost=diversity_max_boost,
        pool=diversity_pool,
        dims=diversity_dims,
    )
    leaf_priorities = float(uniform_priority) * diversity_m[:n]
    if diversity_alpha > 0.0:
        logger.info(
            "Diversity boost: alpha=%.2f resolution=%.2f max_boost=%.2f pool=%s "
            "dims=%s | weight stats min=%.3f max=%.3f mean=%.3f median=%.3f",
            diversity_alpha, diversity_resolution, diversity_max_boost,
            diversity_pool, diversity_dims,
            float(diversity_m.min()), float(diversity_m.max()),
            float(diversity_m.mean()), float(np.median(diversity_m)),
        )

    # Sum-tree: 2C-1 nodes, leaves at [C-1, 2C-1).
    tree = np.zeros(2 * capacity - 1, dtype=np.float64)
    tree[capacity - 1 : capacity - 1 + n] = leaf_priorities
    # Build internal-node sums bottom-up: tree[i] = tree[2i+1] + tree[2i+2].
    for i in range(capacity - 2, -1, -1):
        tree[i] = tree[2 * i + 1] + tree[2 * i + 2]

    # max_priority is the actual leaf max (so subsequent online pushes
    # enter at this ceiling, not at the scalar uniform_priority).
    max_priority = float(leaf_priorities.max()) if n > 0 else float(uniform_priority)

    return {
        "n": np.array(n, dtype=np.int64),
        "capacity": np.array(capacity, dtype=np.int64),
        "obs_pairs": arrays["obs_pairs"][:n],
        "actions": arrays["actions"][:n],
        "rewards": arrays["rewards"][:n].astype(np.float32),
        "terminals": arrays["terminals"][:n],
        "position": np.array(n % capacity, dtype=np.int64),
        "tree": tree,
        "is_demo": is_demo,
        "is_clean": is_clean,
        "episode_returns": episode_returns,
        "max_priority": np.array(max_priority, dtype=np.float64),
        "sample_count": np.array(0, dtype=np.int64),
    }


if __name__ == "__main__":
    # CLI sanity check: print the filter summary for a single archive.
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser()
    parser.add_argument("path", help="Path to a replay_buffer.npz")
    parser.add_argument("--source", choices=["v2", "v3"], default="v2")
    args = parser.parse_args()
    fn = filter_v2 if args.source == "v2" else filter_v3
    r = fn(args.path)
    print(f"kept {r.n_out} / {r.n_in} transitions")
