"""HOST, run once: copy the inputs this package takes from the earlier characterisation workflow into
MRI_GYN_sim/prior/, with a manifest (sha256, source path, producing script).  Units: none (file copy).

    python snapshot_prior.py --src <earlier-workflow scratch dir>      # e.g. .../scratchpad/mri_gyn
    python snapshot_prior.py --verify                                  # check the manifest hashes only

Why: prep_inputs.py, canal_resolution.py, align.py and evaluate.py read eleven files produced by the earlier
workflow (registration, applicator centre lines, sphere pack, HR-CTV-only ICP).  They are NOT regenerated by this
package.  The earlier workflow kept them in a session Temp folder; this snapshot keeps them next to the other
derived data, so the pipeline survives a Temp clean-up.  config.paths()['prior'] points at the snapshot (override:
env APPSIM_PRIOR).
"""
import argparse
import hashlib
import json
import os
import shutil
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config  # noqa: E402

# relative path -> producing script of the earlier workflow (for the manifest)
FILES = {
    "applicator/preBT_IUcanal_centerline_mm.npy": "applicator stage (skeleton centre line of the preBT IUcanal label)",
    "applicator/preBT_IUcanal_centroid_trimmed_smooth_mm.npy": "applicator stage (slice-centroid centre line, trimmed, smoothed)",
    "applicator/BT_IUcanal_centerline_mm.npy": "applicator stage (BT IUcanal = tandem centre line)",
    "sofa/meshes/canal_pre.npy": "sofa/build_meshes.py (preBT canal skeleton)",
    "sofa/meshes/canal_bt.npy": "sofa/build_meshes.py (BT canal skeleton)",
    "proto/design_fast/ovoid_spheres.json": "design stage (14-sphere pack fitted to the BT ovoid label)",
    "proto/design_contact/check_hrctv_icp.json": "design stage (HR-CTV-only surface ICP preBT<->BT)",
    "registration/out/rigid_label_uterus+HRCTV.npz": "registration/s1 label-rigid fit (uterus+HR-CTV; leaky ceiling B1)",
    "registration/out/rigid_mi2_bonyPelvis.npz": "registration/s2c_rigid_mi_v2.py (Mattes MI, peri-organ mask)",
    "registration/out/rigid_mi2_global.npz": "registration/s2c_rigid_mi_v2.py (Mattes MI, whole image)",
    "registration/out/rigid_mi_global_labelcentroid.npz": "registration/s2 (MI from the label-centroid start; E_pelvic)",
}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for b in iter(lambda: fh.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def verify(root):
    man = os.path.join(root, "manifest.json")
    if not os.path.exists(man):
        return ["manifest.json missing in %s (run snapshot_prior.py --src ...)" % root]
    m = json.load(open(man))
    bad = []
    for rel, rec in m["files"].items():
        p = os.path.join(root, rel)
        if not os.path.exists(p):
            bad.append("missing " + rel)
        elif sha(p) != rec["sha256"]:
            bad.append("hash mismatch " + rel)
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=None)
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args()
    dst = config.paths()["prior"]
    if a.verify:
        bad = verify(dst)
        print("prior snapshot OK" if not bad else "PRIOR SNAPSHOT PROBLEMS: %s" % bad)
        sys.exit(1 if bad else 0)
    if not a.src:
        sys.exit("--src <earlier workflow scratch dir> required")
    man = dict(written=time.strftime("%Y-%m-%d %H:%M:%S"), source_root=a.src,
               note="inputs produced by the earlier characterisation workflow; not regenerated by applicator_sim",
               files={})
    for rel, prod in FILES.items():
        s = os.path.join(a.src, rel); d = os.path.join(dst, rel)
        if not os.path.exists(s):
            sys.exit("missing source file: %s" % s)
        os.makedirs(os.path.dirname(d), exist_ok=True)
        shutil.copy2(s, d)
        man["files"][rel] = dict(sha256=sha(d), source=s, produced_by=prod)
    json.dump(man, open(os.path.join(dst, "manifest.json"), "w"), indent=1)
    print("copied %d files -> %s" % (len(FILES), dst))


if __name__ == "__main__":
    main()
