"""S5 of the G32 fix plan, PASS 1 (HOST, python 3.13 with vtk): the tandem-first kinematics gate against the current
wall.  Nothing is simulated: rows are generated by geom.tandem_first_path (the code the scene runs) and checked
against the wall's lumen, the canal and the step limits.  Units mm, deg.  Frame: model = preBT world RAS mm.

    python -P hybrid/tf_gate.py search [--wall vagina_wall_tet26v4] [--app applicator_v4] [--write]
        The rotation-weight search -- the smallest monotone w_r(d) that keeps the tandem body in the wall's rest lumen
        -- for the plan's design, then its fallbacks in order (1 caudal traction <= 5 mm, 2 part of the lift in C).
        --write stores the chosen schedule in <app>/pose.json insertion_path_tandem_first
        (applicator_venezia.tandem_first_record).  Log: hybrid/logs/tf_gate_search.json.
    python -P hybrid/tf_gate.py write [--force]
        The same write from the search log (the chosen mode's L_C re-run; written only if the full gate passes).
    python -P hybrid/tf_gate.py gate --cfg <runs/_cfg/TF0.json> [--tag TF0]
        HOST REPLAY of the run's schedule: scene_hybrid imported with SOFA stubbed, the run's inputs loaded exactly as
        the container loads them, build_schedule(cfg) -> every row checked against the S5 "Accept (pass 1)" list and the
        "Reported" quantities -> hybrid/logs/tf_gate_<tag>.json.
    python -P hybrid/tf_gate.py replay --cfg <runs/_cfg/TF0.json> [--tag TF0]
        The whole scene built on a fake SOFA node API and the controller stepped through every row (+ settle rows) on
        synthetic states (the cervix -- and a corpus_model "fem" corpus -- carried rigidly by the row's corpus
        transform): proves the graph builds without
        the ovoid body, the depth engagement fires as the tip passes each canal_path node, and every log row is written.

DEFINITIONS (the plan's S5 wording; where a choice was needed it is stated and why).
  plan point      C rows: p(d) = T_C(w_r) tau(d) + w_r delta, T_C(w) = Trans(w L_C) o Rot(w theta about O_true),
                  tau = the S3 path (tandem_path.npz) to 20 mm above O_true, then straight along a_lc; delta = the
                  end-of-C offset (tip at Trans(L_C - L) device_final minus T_C(1) tau(d_fin)).  Checked against
                  tandem_path.npz and pose.json directly, not against the record's own polyline.
  containment     tf_metrics' definition (S0): tandem-body points below the wall's top station and above its introitus
                  station, outside the cervix and the corpus (rest surfaces carried rigidly by the row's corpus
                  transform), must be inside the closed lumen sheet by signed distance.  CLEARANCE is measured to the
                  lumen WALL (the inner sheet's own triangles), not to the fan discs that close the sheet at the
                  introitus and the top: those discs are not tissue, and every point within 1 mm above the introitus
                  plane would otherwise "fail" (MEASURED: the V rows' minimum S0 clearance, 0.05-0.55 mm, is the
                  introitus disc).  S0's closed-sheet value is reported beside it.  Points: every vertex and edge
                  midpoint of tube.obj + shaft.obj (edges up to 3.45 mm).
  lower canal     lower_canal_in_tube_frac as S0: labelled canal points (tandem_path pts, 0 <= s <= min(d, 20)),
                  carried rigidly with the corpus, within r_tube + 1 mm of the tube segment flange..tip.
  L proxy lumen   the G32 final wall (runs/G32/final/vagina.obj: the lumen necked to 18.2-19.2 mm).
  apex lift       the scene's formula (apex_attach "lift"): the mean axial (wall axis) displacement of the cervix nodes
                  paired with the apex nodes (apex_lift_pair, nearest at rest), here carried rigidly by the corpus
                  transform -- an estimate, the FEM cervix below the attach interface lags the corpus.

Patient-derived output: local only."""
import argparse
import json
import os
import sys
import time
import types

sys.dont_write_bytecode = True                      # never leave __pycache__ in the repo
os.environ.setdefault("MPLBACKEND", "Agg")

import numpy as np  # noqa: E402
import vtk  # noqa: E402
from vtk.util import numpy_support as ns  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__)).replace("\\", "/")
PARENT = os.path.dirname(HERE)
for _p in (HERE, PARENT):
    if _p not in sys.path:
        sys.path.insert(0, _p)
import geom  # noqa: E402
import tandem_path as TP  # noqa: E402
import tf_metrics as TM  # noqa: E402
from vagina_wall import read_vtk_legacy  # noqa: E402

VERSION = "tf_gate/1.0 (fix plan S5 pass 1)"
HYB = TM.HYB
MESHES = HYB + "/meshes"
LOGS = HYB + "/logs"
PARTS = ("tube", "shaft")

# Every number here is the plan's (S5 / S6) unless marked.
OPT = dict(
    wall="vagina_wall_tet26v4", app="applicator_v4", ref_run="G32",
    clear_mm=1.0,             # containment clearance (plan S5)
    search_margin_mm=0.25,    # ASSUMED: the search asks 1.25 mm on vertices so the gate's 1.0 holds on the densified
                              #   points and leaves room for the FEM cervix (not rigid) in the run
    frac_min=0.9,             # lower_canal_in_tube_frac (plan S5 / S6)
    frac_margin_mm=0.25,      # ASSUMED: the tube axis rule keeps the canal within r_tube + 1 - 0.25 mm
    d_gate_mm=5.0,            # the canal gate applies after d = 5 mm (plan)
    follow_mm=20.0,           # tau follows the labelled canal this far (plan)
    v_below_mm=4.0,           # ASSUMED: V starts with the tip this far below the path's introitus end (device outside)
    v_step_mm=1.0,            # V: <= 1 mm tip travel per step (plan)
    c_step_mm=1.0,            # C: <= 1.0 mm tip travel per step (plan) -- also the largest depth increment tried
    c_step_min_mm=0.02,
    axis_step_deg=0.8,        # C: <= 0.8 deg axis per step (plan)
    corpus_step_mm=1.0,       # ASSUMED: <= 1 mm of corpus surface travel per step in C (G2's safe device rate 1.4)
    l_step_mm=0.5,            # L: <= 0.5 mm per step (plan)
    traction_mm=5.0,          # fallback 1: caudal traction <= 5 mm along -a_v (plan)
    fit_w_os=5.0,             # ASSUMED: weight of the carried O_true in the axis fit ("through the carried O_true")
    fit_min_mm=1.0,           # below this depth the traversed canal is too short to fit: the axis stays
    blend_sigma0=0.8,         # ASSUMED: the axis is blended onto a_fin over the last 20 % of C's (d, w) progress
    extrap_chord_mm=10.0,     # direction of the path's extension below the introitus: the chord of its lowest 10 mm
    w_bisect=7,               # bisection steps for the smallest feasible w_r (resolution 1/128 of the remaining range)
    f_bisect=6,               # bisection steps for the smallest fraction of the lift in C (fallback 2)
)


def rnd(x, n=3):
    return TM.rnd(x, n)


def _jsonable(o):
    if isinstance(o, dict):
        return {k: _jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_jsonable(v) for v in o]
    if isinstance(o, np.ndarray):
        return _jsonable(o.tolist())
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, np.bool_):
        return bool(o)
    return o


class Dist:
    """Unsigned distance to an OPEN triangle sheet (vtkImplicitPolyDataDistance magnitude; its sign is meaningless on
    an open sheet and is not used)."""

    def __init__(self, V, F):
        self.imp = vtk.vtkImplicitPolyDataDistance()
        self.imp.SetInput(TM.polydata(V, F))

    def __call__(self, P):
        P = np.atleast_2d(np.asarray(P, float))
        if not len(P):
            return np.zeros(0)
        arr = vtk.vtkDoubleArray()
        self.imp.FunctionValue(ns.numpy_to_vtk(np.ascontiguousarray(P), deep=1), arr)
        return np.abs(ns.vtk_to_numpy(arr))


def edge_midpoints(V, F):
    E = np.unique(np.sort(np.vstack([F[:, [0, 1]], F[:, [1, 2]], F[:, [2, 0]]]), axis=1), axis=0)
    return 0.5 * (V[E[:, 0]] + V[E[:, 1]])


# ============================================================================================ geometry context
class Geo:
    """Everything the gate needs, read once."""

    def __init__(self, wall=OPT["wall"], app=OPT["app"], ref_run=OPT["ref_run"]):
        self.wall_dir, self.app_dir = wall, app
        self.T = TP.load()
        s = self.T["s"]
        self.ic = np.nonzero(s >= 0)[0]
        self.canal = self.T["pts"][self.ic]
        self.canal_s = s[self.ic]
        self.O = np.asarray(self.T["O_true"], float)
        self.a_lc = geom.unit(self.T["a_lc"])
        self.s_ios = float(self.T["s_internal_os"])
        # applicator (tandem body) + the validated pose at the default Delta
        self.appd = "%s/%s" % (HYB, app)
        self.appj = json.load(open(self.appd + "/applicator.json"))
        self.pose = json.load(open(self.appd + "/pose.json"))
        pv = self.appj["params"]
        self.L_iu = float(pv["L_iu_mm"]["value"])
        self.r_tube = float(pv["r_tandem_mm"]["value"])
        self.delta_shift = float(self.pose["default_flange_shift_mm"])
        tbl = self.pose["corpus"]["by_flange_shift_mm"]
        key = [k for k in tbl if abs(float(k) - self.delta_shift) < 1e-9][0]
        e = tbl[key]
        df = self.pose["device_final"]
        self.F_fin = np.asarray(e["flange"], float)
        self.T_final = np.asarray(e["T_preBT_to_target"], float)
        self.a_fin = geom.unit(df["tube_axis"])
        self.R_fin_json = np.asarray(df["R_rows"], float)
        self.x_fin = geom.ortho(self.R_fin_json[0], self.a_fin)
        self.split = geom.corpus_split(self.T_final, self.O)
        self.d_F = float(self.T["d_F"])
        self.d_fin = self.L_iu - self.d_F
        # device points in the applicator frame: vertices + edge midpoints
        P, part, isv = [], [], []
        for p in PARTS:
            V, F = geom.read_obj("%s/%s.obj" % (self.appd, p))
            M = edge_midpoints(V, F)
            P += [V, M]
            part += [p] * (len(V) + len(M))
            isv += [True] * len(V) + [False] * len(M)
        self.P_app = np.vstack(P)
        self.part = np.array(part)
        self.isv = np.array(isv)
        # the wall and the organs as the scene loads them (scene root; read only here)
        root = "%s/_scene_%s" % (MESHES, wall)
        if not os.path.exists(root + "/vagina/meta.json"):
            raise SystemExit("no scene mesh root %s (run the wall once, or vagina_wall.scene_mesh_root)" % root)
        self.root = root
        self.meta_v = json.load(open(root + "/vagina/meta.json"))
        self.meta_c = json.load(open(root + "/cervix/meta.json"))
        self.wall = TM.Wall(self.meta_v, {})
        self.a_w = geom.unit(self.meta_v["axis"]["axis"])
        Vv, Fv = geom.read_obj(root + "/vagina/surface.obj")
        self.lum_rest = self.lumen(Vv, Fv, "rest %s" % wall)
        rest = {b: geom.read_obj("%s/%s/surface.obj" % (root, b)) for b in ("cervix", "corpus", "bladder", "rectum")}
        self.rest = rest
        self.surf = {b: TM.Surf(*rest[b], b) for b in rest}
        self.corpus_V = rest["corpus"][0]
        self.cervix_V = rest["cervix"][0]
        # apex lift pairing, as scene_hybrid._add_couplings ("lift", apex_lift_pair "canal")
        Xv0, _ = read_vtk_legacy(root + "/vagina/tets.vtk")
        Xc0, _ = read_vtk_legacy(root + "/cervix/tets.vtk")
        self.Xc0 = Xc0
        apex = np.asarray(self.meta_v["node_sets"]["apex"], int)
        cset = np.asarray(self.meta_c["node_sets"]["canal"], int)
        dd = np.linalg.norm(Xv0[apex][:, None, :] - Xc0[cset][None, :, :], axis=2)
        self.apex_pair = cset[dd.argmin(1)]
        # the L-phase proxy lumen: the G32 final wall (necked)
        gv = "%s/runs/%s/final/vagina.obj" % (HYB, ref_run)
        self.lum_ref = self.lumen(*geom.read_obj(gv), "%s final" % ref_run) if os.path.exists(gv) else None

    def lumen(self, V, F, name):
        closed, _ = self.wall.sheets(V, F)
        Fi = np.asarray(F, int)[self.wall.inner_v[np.asarray(F, int)].all(1)]
        return dict(name=name, closed=closed, sheet=Dist(V, Fi), st=self.wall.stations(V), V=np.asarray(V, float))

    # ---- one row
    def points(self, row, verts_only=False):
        X = np.asarray(row["F"], float) + self.P_app @ np.asarray(row["R_rows"], float)
        return (X[self.isv], self.part[self.isv]) if verts_only else (X, self.part)

    def in_tissue(self, X, Tc):
        Tc = np.asarray(Tc, float)
        Xr = (X - Tc[:3, 3]) @ Tc[:3, :3]                  # into the rest frame of the corpus / cervix
        return (self.surf["cervix"].sd(Xr, 1.0) <= 0) | (self.surf["corpus"].sd(Xr, 1.0) <= 0)

    def contain(self, row, lum, verts_only=False, clear_mm=OPT["clear_mm"], lift=None):
        """Containment of the tandem body in `lum` (see DEFINITIONS).  lift (mm, default: the row's apex lift estimate
        for the REST lumen, 0 for any other): the scene lifts the wall's top with the paired canal nodes, so the lumen
        is taken as the rest lumen stretched linearly along the wall axis from the introitus (0) to the lifted top
        (H + lift): a point at height h is tested at h H / (H + lift).  Tissue is tested at the true position."""
        X, part = self.points(row, verts_only)
        c, t = lum["st"]["c"], lum["st"]["t"]
        if lift is None:
            lift = self.apex_lift(row["T_corpus"]) if lum is self.lum_rest else 0.0
        H = float((c[-1] - c[0]) @ self.a_w)
        hw = (X - c[0]) @ self.a_w
        Xm = X - np.outer(hw * float(lift) / (H + float(lift)), self.a_w) if abs(lift) > 1e-9 else X
        h_top = (Xm - c[-1]) @ t[-1]
        h_bot = (Xm - c[0]) @ t[0]
        tis = self.in_tissue(X, row["T_corpus"])
        cons = (h_top <= 0) & (h_bot >= 0) & ~tis
        out = dict(lumen=lum["name"], apex_lift_mm=float(lift), n_points=int(len(X)), n_in_tissue=int(tis.sum()),
                   n_above_top=int((h_top > 0).sum()), n_below_introitus=int((h_bot < 0).sum()),
                   n_considered=int(cons.sum()))
        if not cons.any():
            out.update(ok=True, min_clear_mm=None)
            return out
        Xc = Xm[cons]
        sl = lum["closed"].sd(Xc, None)
        dw = lum["sheet"](Xc)
        clr = np.where(sl < 0, dw, -dw)
        j = int(np.argmin(clr))
        out.update(ok=bool(clr.min() >= clear_mm), min_clear_mm=float(clr.min()), n_outside_lumen=int((sl >= 0).sum()),
                   n_clear_lt=int((clr < clear_mm).sum()), min_clear_closed_sheet_mm=float(-sl.max()),
                   worst=dict(part=str(part[cons][j]), h_above_introitus_mm=float(h_bot[cons][j]), xyz=Xc[j].tolist()))
        return out

    def canal_fracs(self, row):
        """S0's canal-against-tube numbers for a row (labelled canal carried rigidly by the row's corpus)."""
        d = float(row["d_mm"])
        Tc = np.asarray(row["T_corpus"], float)
        cc = self.canal @ Tc[:3, :3].T + Tc[:3, 3]
        a = geom.unit(row["tube_axis"])
        dseg, h = TM.seg_dist(cc, np.asarray(row["F"], float), a, self.L_iu)
        within = dseg <= self.r_tube + TM.TUBE_TOL_MM
        cs = self.canal_s
        lower = (cs >= 0) & (cs <= min(d, OPT["follow_mm"]))
        inspan = (h >= 0) & (h <= self.L_iu)
        up = cs > OPT["follow_mm"]
        return dict(lower=float(within[lower].mean()) if (d > 0 and lower.any()) else None,
                    lower_max_dist_mm=float(dseg[lower].max()) if (d > 0 and lower.any()) else None,
                    traversed=float(within[inspan].mean()) if inspan.any() else None,
                    upper_residual_mm=float(dseg[up].max()) if up.any() else None)

    def apex_lift(self, Tc):
        Tc = np.asarray(Tc, float)
        X = self.Xc0[self.apex_pair]
        return float((((X @ Tc[:3, :3].T + Tc[:3, 3]) - X) @ self.a_w).mean())

    # ---- the S5 plan point, independently of the record's polyline
    def tau_s3(self, d):
        d = np.atleast_1d(np.asarray(d, float))
        f = OPT["follow_mm"]
        return TP.interp_path(self.T["pts"], self.T["s"], np.minimum(d, f)) + np.outer(np.maximum(d - f, 0.0), self.a_lc)

    def T_C(self, w, L_C):
        sp = self.split
        return geom.tf_corpus_T(sp["pivot"], sp["axis"], sp["theta_deg"], w, L_C)


# ============================================================================================ the schedule parameters
def base_params(geo, L_C, opt=OPT):
    """The record's params for a lift-in-C vector L_C (zero = the plan's design): the planned path tau as a polyline
    (the path's extension below the introitus, the path to follow_mm, the straight a_lc extension to past d_fin), the
    corpus split, delta, the final pose, the axis-rule constants.  V / C / L knots are filled by the search."""
    T = geo.T
    s, pts = T["s"], T["pts"]
    fol = opt["follow_mm"]
    L = geo.L_iu
    v0 = float(s[0]) - opt["v_below_mm"]
    e = geom.unit(pts[0] - TP.interp_path(pts, s, [float(s[0]) + opt["extrap_chord_mm"]])[0])
    n_b = int(np.ceil(float(s[0]) - (v0 - L - 2.0)))
    qb = float(s[0]) - np.arange(n_b, 0, -1, dtype=float)
    below = pts[0] + np.outer(float(s[0]) - qb, e)
    keep = s <= fol + 1e-9
    tf_ = TP.interp_path(pts, s, [fol])[0]
    n_a = int(np.ceil(geo.d_fin + 5.0 - fol))
    qa = fol + np.arange(1, n_a + 1, dtype=float)
    above = tf_ + np.outer(qa - fol, geo.a_lc)
    tau_s = np.r_[qb, s[keep], qa]
    tau_pts = np.vstack([below, pts[keep], above])
    sp = geo.split
    Rw = geom.rodrigues(sp["axis"], sp["theta_deg"])
    tip_endC = geo.F_fin - sp["L"] + L * geo.a_fin
    tau_fin = geom.polyline_at(tau_pts, tau_s, [geo.d_fin])[0]
    delta = tip_endC - (Rw @ (tau_fin - sp["pivot"]) + sp["pivot"])
    return dict(tau_pts=tau_pts, tau_s=tau_s, follow_mm=fol, pivot=sp["pivot"], rot_axis=sp["axis"],
                theta_deg=sp["theta_deg"], L=sp["L"], L_C=np.asarray(L_C, float), delta=delta, L_iu=L,
                F_fin=geo.F_fin, a_fin=geo.a_fin, x_fin=geo.x_fin, d_fin=geo.d_fin,
                frac_min=opt["frac_min"], frac_tol_mm=geo.r_tube + TM.TUBE_TOL_MM - opt["frac_margin_mm"],
                fit_w_os=opt["fit_w_os"], fit_min_mm=opt["fit_min_mm"], blend_sigma0=opt["blend_sigma0"],
                V_start_s=v0, V_tip_s=[], C_knots=[], L_w=[])


def v_knots(prm, opt=OPT):
    v0 = float(prm["V_start_s"])
    n = int(np.ceil(-v0 / opt["v_step_mm"] - 1e-9))
    return [v0 + (0.0 - v0) * k / n for k in range(1, n + 1)]


def l_knots(prm, opt=OPT):
    L_rem = float(np.linalg.norm(np.asarray(prm["L"], float) - np.asarray(prm["L_C"], float)))
    n = max(1, int(np.ceil(L_rem / opt["l_step_mm"] - 1e-9)))
    return [k / float(n) for k in range(1, n + 1)]


def step_info(geo, r0, r1):
    """Per-step motion between two rows: tip travel, axis turn, corpus surface travel, device point travel."""
    t0, t1 = np.asarray(r0["F"], float) + geo.L_iu * geom.unit(r0["tube_axis"]), \
        np.asarray(r1["F"], float) + geo.L_iu * geom.unit(r1["tube_axis"])
    T0, T1 = np.asarray(r0["T_corpus"], float), np.asarray(r1["T_corpus"], float)
    V = geo.corpus_V
    dc = np.linalg.norm((V @ T1[:3, :3].T + T1[:3, 3]) - (V @ T0[:3, :3].T + T0[:3, 3]), axis=1).max()
    X0 = np.asarray(r0["F"], float) + geo.P_app[geo.isv] @ np.asarray(r0["R_rows"], float)
    X1 = np.asarray(r1["F"], float) + geo.P_app[geo.isv] @ np.asarray(r1["R_rows"], float)
    dX = np.linalg.norm(X1 - X0, axis=1)
    st = geo.lum_rest["st"]
    inb = ((X1 - st["c"][0]) @ st["t"][0] >= 0) | ((X0 - st["c"][0]) @ st["t"][0] >= 0)   # above the introitus plane
    return dict(tip_mm=float(np.linalg.norm(t1 - t0)), axis_deg=geom.angle_deg(r0["tube_axis"], r1["tube_axis"]),
                corpus_mm=float(dc), device_mm=float(dX.max()),
                device_in_body_mm=float(dX[inb].max()) if inb.any() else 0.0)


# ============================================================================================ the search
def search_C(geo, prm, opt=OPT, d_ramp=None):
    """Smallest monotone w_r(d): walk d from 0 to d_fin in steps of at most c_step_mm (halved while a step breaks a
    per-step limit); at each depth take the smallest w >= max(the previous one, the ramp floor) whose row keeps the
    tandem body in the rest lumen with clear_mm + search_margin_mm (vertices) and the lower canal in the tube (after
    d_gate_mm).  Feasibility is NOT monotone in w (MEASURED: the rotation swings the rod one way, the lift-in-C
    translation the other), so w is scanned upward in 0.05 steps and the first feasible interval refined by bisection.
    w = 1 must hold at d_fin: the ramp floor clip((d - d_ramp) / (d_fin - d_ramp), 0, 1) (None: no floor, the rest of
    the rotation at constant depth, still checked).  Returns dict(ok, knots, why, stage, ...)."""
    need = opt["clear_mm"] + opt["search_margin_mm"]
    lim = dict(tip_mm=opt["c_step_mm"], axis_deg=opt["axis_step_deg"], corpus_mm=opt["corpus_step_mm"])
    n_eval = [0]

    def feasible(row):
        n_eval[0] += 1
        c = geo.contain(row, geo.lum_rest, verts_only=True)
        fr = geo.canal_fracs(row)["lower"]
        f_ok = (row["d_mm"] <= opt["d_gate_mm"]) or (fr is not None and fr >= opt["frac_min"])
        return bool((c["min_clear_mm"] is None or c["min_clear_mm"] >= need) and f_ok), c, fr

    def limits_ok(r0, r1):
        si = step_info(geo, r0, r1)
        return all(si[k] <= v + 1e-9 for k, v in lim.items()), si

    prev = geom.tf_row_V(prm, 0.0)
    d, w = 0.0, 0.0
    d_fin = float(prm["d_fin"])
    knots, trace = [], []
    while not (d >= d_fin - 1e-12 and w >= 1.0 - 1e-12):
        if d < d_fin - 1e-12:
            dd = min(opt["c_step_mm"], d_fin - d)
            while True:
                d1 = d_fin if d + dd >= d_fin - 1e-9 else d + dd
                ap = prev["tube_axis"]
                w_lo = w
                if d_ramp is not None and d1 > d_ramp:
                    w_lo = max(w, min(1.0, (d1 - d_ramp) / max(1e-9, d_fin - d_ramp)))
                row = geom.tf_row_C(prm, d1, w_lo, ap)
                ok, c, fr = feasible(row)
                w1 = w_lo
                if not ok:
                    grid = list(np.arange(w_lo + 0.05, 1.0, 0.05)) + [1.0]
                    lo, r1, best = w_lo, None, dict(w=w_lo, clear=c.get("min_clear_mm"), frac=fr)
                    for wg in grid:
                        rg = geom.tf_row_C(prm, d1, float(wg), ap)
                        okg, cg, frg = feasible(rg)
                        if okg:
                            r1, hi = rg, float(wg)
                            break
                        lo = float(wg)
                        if cg.get("min_clear_mm") is not None and (best["clear"] is None or cg["min_clear_mm"] > best["clear"]):
                            best = dict(w=float(wg), clear=cg["min_clear_mm"], frac=frg, worst=cg.get("worst"))
                    if r1 is None:
                        return dict(ok=False, stage="depth", knots=knots, why="no w_r in [%.3f, 1] keeps the tandem in "
                                    "the lumen at d = %.2f mm" % (w_lo, d1), fail_d_mm=d1, clear_at_w=c.get("min_clear_mm"),
                                    frac_at_w=fr, best_in_scan=best, n_eval=n_eval[0], trace=trace)
                    rh = r1
                    for _ in range(int(opt["w_bisect"])):
                        mid = 0.5 * (lo + hi)
                        rm = geom.tf_row_C(prm, d1, mid, ap)
                        if feasible(rm)[0]:
                            hi, rh = mid, rm
                        else:
                            lo = mid
                    w1, row = hi, rh
                l_ok, si = limits_ok(prev, row)
                if l_ok:
                    break
                if dd <= opt["c_step_min_mm"]:
                    return dict(ok=False, stage="rate", knots=knots, why="per-step limit broken at d = %.2f even with a %.3f mm step: %s"
                                % (d1, dd, {k: round(v, 3) for k, v in si.items()}), fail_d_mm=d1, n_eval=n_eval[0],
                                trace=trace)
                dd *= 0.5
        else:                                               # at d_fin: finish the rotation at constant depth
            dw = 1.0 - w
            while True:
                w1 = min(1.0, w + dw)
                row = geom.tf_row_C(prm, d_fin, w1, prev["tube_axis"])
                ok = feasible(row)[0]
                l_ok, si = limits_ok(prev, row)
                if ok and l_ok:
                    d1 = d_fin
                    break
                if dw < 1e-4:
                    cf = geo.contain(row, geo.lum_rest, verts_only=True)
                    return dict(ok=False, stage="final_ramp", knots=knots, why="the rotation cannot be finished at "
                                "d_fin: w %.3f -> %.3f (containment %s, limits %s)" % (w, w1, ok, l_ok),
                                fail_d_mm=d_fin, fail_w=w1, clear=cf.get("min_clear_mm"), worst=cf.get("worst"),
                                n_eval=n_eval[0], trace=trace)
                dw *= 0.5
        knots.append([float(d1), float(w1)])
        trace.append(dict(d=round(d1, 3), w=round(w1, 4), clear=None))
        prev, d, w = row, d1, w1
    return dict(ok=True, stage="done", knots=knots, why="", n_eval=n_eval[0], n_C=len(knots))


def run_mode(geo, name, L_C, opt=OPT):
    """One lift-in-C vector: V knots, the C search (first without a ramp floor; if only the final rotation at d_fin
    fails, with the ramp starting ever earlier, 5 mm at a time: the LATEST start that works = the smallest w_r), L."""
    t0 = time.time()
    prm = base_params(geo, L_C, opt)
    prm["V_tip_s"] = v_knots(prm, opt)
    d_fin = float(prm["d_fin"])
    res = search_C(geo, prm, opt)
    res["d_ramp"] = None
    tried_ramps = []
    if not res["ok"] and res["stage"] in ("final_ramp", "rate"):
        for d_r in np.arange(d_fin - 5.0, -1e-9, -5.0):
            r2 = search_C(geo, prm, opt, d_ramp=float(d_r))
            tried_ramps.append(dict(d_ramp=round(float(d_r), 3), ok=r2["ok"], stage=r2["stage"], why=r2["why"]))
            if r2["ok"] or r2["stage"] == "depth":
                res = r2
                res["d_ramp"] = float(d_r)
                break
    res["tried_ramps"] = tried_ramps
    prm["C_knots"] = res["knots"]
    prm["L_w"] = l_knots(prm, opt)
    res.update(mode=name, L_C=np.asarray(L_C, float).tolist(), wall_s=round(time.time() - t0, 1))
    print("  [%s] L_C %s: %s%s (%d C knots, ramp from %s, %d evals, %.0f s)" % (
        name, np.round(L_C, 2).tolist(), "PASS" if res["ok"] else "FAIL", "" if res["ok"] else " -- " + res["why"],
        len(res["knots"]), res.get("d_ramp"), res.get("n_eval", 0), res["wall_s"]), flush=True)
    return res, prm


def lift_vectors(geo):
    L = geo.split["L"]
    a_v = geo.a_w
    return dict(L=L, a_v=a_v, L_axial=float(L @ a_v), L_perp=L - float(L @ a_v) * a_v)


def cmd_search(a):
    geo = Geo(a.wall, a.app, a.ref_run)
    lv = lift_vectors(geo)
    sp = geo.split
    print("[search] O_true %s; L %s |L| %.2f (along a_v %.2f, lateral %.2f); theta %.3f deg; d_fin %.3f" % (
        np.round(geo.O, 2).tolist(), np.round(sp["L"], 2).tolist(), np.linalg.norm(sp["L"]), lv["L_axial"],
        np.linalg.norm(lv["L_perp"]), sp["theta_deg"], geo.d_fin), flush=True)
    tried, chosen, pass1_diag = [], None, None
    # the plan's design: no lift in C
    res, prm = run_mode(geo, "pass1", np.zeros(3))
    tried.append(res)
    if res["ok"]:
        chosen = ("pass1", res, prm, dict(fallback=None))
    else:
        # where the design fails at the gate's OWN threshold (no search margin), and how far out the best w_r is
        # at the depths that follow, so the failure is not an artefact of the 0.25 mm margin
        o0 = dict(OPT, search_margin_mm=0.0)
        r0, p0 = run_mode(geo, "pass1_no_margin", np.zeros(3), o0)
        tried.append(r0)
        prof = []
        for d in (15.0, 20.0, 25.0, 30.0, 35.0, 40.0, geo.d_fin):
            best = None
            ap = geom.tf_row_V(p0, 0.0)["tube_axis"]
            for w in np.linspace(0.0, 1.0, 11):
                # the axis the least-motion rule would reach from the V end (a lower bound on the lag; the table
                # shows the landscape, not a schedule)
                row = geom.tf_row_C(p0, d, float(w), ap)
                c = geo.contain(row, geo.lum_rest, verts_only=True)
                if c["min_clear_mm"] is not None and (best is None or c["min_clear_mm"] > best[1]):
                    best = (float(w), c["min_clear_mm"], c["worst"])
            prof.append(dict(d_mm=round(d, 2), best_w=best[0], best_clear_mm=round(best[1], 2), worst=best[2]))
            print("    pass1 landscape: d %5.1f  best w_r %.1f  clearance %6.2f mm (%s at %.1f mm above the introitus)" % (
                d, best[0], best[1], best[2]["part"], best[2]["h_above_introitus_mm"]), flush=True)
        pass1_diag = dict(no_margin=dict(ok=r0["ok"], why=r0["why"], fail_d_mm=r0.get("fail_d_mm"),
                                         best_in_scan=r0.get("best_in_scan")), landscape=prof)
    # fallback 1: caudal traction <= 5 mm along -a_v (tenaculum), flagged
    if chosen is None:
        res, prm = run_mode(geo, "fallback1_traction", -OPT["traction_mm"] * lv["a_v"])
        tried.append(res)
        if res["ok"]:
            # the smallest traction that passes
            lo, hi, best = 0.0, OPT["traction_mm"], (res, prm)
            for _ in range(4):
                mid = 0.5 * (lo + hi)
                r2, p2 = run_mode(geo, "fallback1_traction", -mid * lv["a_v"])
                if r2["ok"]:
                    hi, best = mid, (r2, p2)
                else:
                    lo = mid
            chosen = ("fallback1_traction", best[0], best[1], dict(fallback=1, traction_mm=hi))
    # fallback 2: part of the lift in C (flagged "non-clinical").  Two readings, both searched for the smallest part:
    #   "fraction": L_C = f L (the literal wording); "lateral": L_C = f L_perp, the part of L perpendicular to the
    #   vaginal axis -- no cranial lift along the vagina in C.  The one with the smaller rise along the vaginal axis
    #   is chosen: the plan separates rotation and lift because the CRANIAL lift in C tears the vault from the portio.
    if chosen is None:
        cands = []
        for name, vec in (("fallback2_fraction", lv["L"]), ("fallback2_lateral", lv["L_perp"])):
            r1, p1 = run_mode(geo, name, vec)
            tried.append(r1)
            if not r1["ok"]:
                continue
            lo, hi, best = 0.0, 1.0, (r1, p1)
            for _ in range(int(OPT["f_bisect"])):
                mid = 0.5 * (lo + hi)
                r2, p2 = run_mode(geo, name, mid * vec)
                tried.append(r2)
                if r2["ok"]:
                    hi, best = mid, (r2, p2)
                else:
                    lo = mid
            L_C = hi * vec
            cands.append((float(L_C @ lv["a_v"]), name, best[0], best[1],
                          dict(fallback=2, reading=name.split("_")[1], fraction=hi, L_C=L_C.tolist(),
                               L_C_norm_mm=float(np.linalg.norm(L_C)), L_C_along_a_v_mm=float(L_C @ lv["a_v"]),
                               L_C_z_mm=float(L_C[2]), fraction_of_L_norm=float(np.linalg.norm(L_C) / np.linalg.norm(lv["L"])))))
        if cands:
            cands.sort(key=lambda c: c[0])
            chosen = (cands[0][1], cands[0][2], cands[0][3], dict(cands[0][4], alternatives=[c[4] for c in cands[1:]]))
    out = dict(version=VERSION, written=time.strftime("%Y-%m-%d %H:%M:%S"), wall=a.wall, app=a.app, opt=OPT,
               decomposition=dict(pivot=geo.O, L=sp["L"], L_norm_mm=float(np.linalg.norm(sp["L"])),
                                  theta_deg=sp["theta_deg"], axis=sp["axis"], L_along_a_v_mm=lv["L_axial"],
                                  L_perp_mm=lv["L_perp"], d_fin_mm=geo.d_fin),
               tried=[{k: v for k, v in t.items() if k != "trace"} for t in tried], pass1_diagnosis=pass1_diag,
               chosen=None if chosen is None else dict(mode=chosen[0], **chosen[3]))
    if chosen is None:
        out["verdict"] = "FAIL: no schedule keeps the tandem inside the %s lumen; fallback 3 = skip TF0 (TF1a)" % a.wall
        print("[search] " + out["verdict"], flush=True)
    else:
        name, res, prm, info = chosen
        out["chosen"]["L_C"] = np.asarray(prm["L_C"], float).tolist()
        out["chosen"]["d_ramp"] = res.get("d_ramp")
        g = evaluate_rows(geo, geom.tandem_first_path(prm), prm)
        out["gate"] = g["summary"]
        out["verdict"] = "%s: %s" % (name, "PASS" if g["summary"]["pass_all"] else "FAIL on the full gate")
        print("[search] chosen %s; full gate pass_all %s" % (name, g["summary"]["pass_all"]), flush=True)
    os.makedirs(LOGS, exist_ok=True)
    fn = LOGS + "/tf_gate_search.json"
    json.dump(_jsonable(out), open(fn, "w"), indent=1)
    print("[search] log %s" % fn, flush=True)
    if a.write and chosen is not None:
        write_chosen(geo, out, a, prm=chosen[2], res=chosen[1])


def write_chosen(geo, log, a, prm=None, res=None):
    """Store the chosen schedule in <app>/pose.json (applicator_venezia.tandem_first_record).  From a finished search
    (`search --write`) or from its log (`write`: the chosen L_C is re-run -- the search is deterministic -- and the
    full gate re-evaluated; nothing is written unless the gate passes, or --force)."""
    import applicator_venezia as AV
    ch = log.get("chosen")
    if not ch:
        raise SystemExit("write: the search log has no chosen schedule (%s)" % log.get("verdict"))
    if prm is None:
        res, prm = run_mode(geo, ch["mode"], np.asarray(ch["L_C"], float))
        if not res["ok"]:
            raise SystemExit("write: re-running %s did not reproduce a passing search: %s" % (ch["mode"], res["why"]))
    g = evaluate_rows(geo, geom.tandem_first_path(prm), prm)
    if not g["summary"]["pass_all"] and not a.force:
        raise SystemExit("write: the full gate fails for %s (see %s); nothing written (--force to write anyway)"
                         % (ch["mode"], LOGS + "/tf_gate_search.json"))
    lv = lift_vectors(geo)
    L_C = np.asarray(prm["L_C"], float)
    info = dict(mode=ch["mode"], fallback=dict({k: v for k, v in ch.items() if k not in ("mode",)}),
                lift_in_C=dict(L_C=L_C.tolist(), L_C_norm_mm=float(np.linalg.norm(L_C)),
                               along_a_v_mm=float(L_C @ lv["a_v"]), z_mm=float(L_C[2]),
                               flag=(None if ch["mode"] == "pass1" else "non-clinical (fix plan S5 fallback)")),
                pass1_diagnosis=log.get("pass1_diagnosis"),
                verdict="%s: %s" % (ch["mode"], "PASS" if g["summary"]["pass_all"] else "FAIL on the full gate (--force)"),
                search=dict(n_eval=(res or {}).get("n_eval"), n_C=len(prm["C_knots"]), d_ramp=(res or {}).get("d_ramp"),
                            opt=OPT, tried=[dict(mode=t.get("mode"), L_C=t.get("L_C"), ok=t.get("ok"), why=t.get("why"))
                                            for t in log.get("tried", [])]),
                gate=g["summary"])
    rec = AV.tandem_first_record(geo.appd, prm, info, wall=geo.wall_dir)
    print("[write] %s/pose.json insertion_path_tandem_first: mode %s, %d rows (V %d, C %d, L %d), gate pass_all %s"
          % (geo.appd, ch["mode"], len(rec["rows"]), rec["n_rows"]["V"], rec["n_rows"]["C"], rec["n_rows"]["L"],
             g["summary"]["pass_all"]), flush=True)


# ============================================================================================ the gate
def smoothstep(x):
    return geom.smoothstep(x)


def evaluate_rows(geo, rows, prm, opt=OPT):
    """Every S5 pass-1 check on the V / C / L rows, and the reported quantities."""
    L_C = np.asarray(prm["L_C"], float)
    delta = np.asarray(prm["delta"], float)
    sp = geo.split
    L = sp["L"]
    ph = [r["phase"] for r in rows]
    per = []
    start = geom.tf_row_V(prm, float(prm["V_start_s"]))
    prev = start
    for i, r in enumerate(rows):
        e = dict(i=i, phase=r["phase"], d_mm=float(r["d_mm"]), w_r=float(r["w_r"]), w_l=float(r["w_l"]))
        e["step"] = step_info(geo, prev, r)
        lum = geo.lum_ref if r["phase"] == "L" else geo.lum_rest
        e["contain"] = geo.contain(r, lum) if lum is not None else None
        if r["phase"] == "L":                                   # also against the rest lumen, for reference
            e["contain_rest"] = geo.contain(r, geo.lum_rest)
        e["canal"] = geo.canal_fracs(r)
        e["apex_lift_mm"] = geo.apex_lift(r["T_corpus"])
        tip = np.asarray(r["F"], float) + geo.L_iu * geom.unit(r["tube_axis"])
        if r["phase"] == "C":
            Tc = geo.T_C(r["w_r"], L_C)
            p = Tc[:3, :3] @ geo.tau_s3(r["d_mm"])[0] + Tc[:3, 3] + r["w_r"] * delta
            e["tip_to_plan_mm"] = float(np.linalg.norm(tip - p))
            e["corpus_vs_plan_mm"] = float(np.abs(np.asarray(r["T_corpus"], float) - Tc).max())
        elif r["phase"] == "V" and r["d_mm"] >= float(geo.T["s"][0]):
            e["tip_to_path_mm"] = float(TP.project(tip[None], geo.T["pts"], geo.T["s"])[0][0])
        per.append(e)
        prev = r
    iV = [i for i, p in enumerate(ph) if p == "V"]
    iC = [i for i, p in enumerate(ph) if p == "C"]
    iL = [i for i, p in enumerate(ph) if p == "L"]

    def mx(idx, f):
        v = [f(per[i]) for i in idx]
        v = [x for x in v if x is not None]
        return max(v) if v else None

    def mn(idx, f):
        v = [f(per[i]) for i in idx]
        v = [x for x in v if x is not None]
        return min(v) if v else None
    acc = []

    def chk(name, measured, ok, limit):
        acc.append(dict(test=name, measured=measured, limit=limit, pass_=bool(ok)))
    # tip vs plan
    tp = mx(iC, lambda e: e["tip_to_plan_mm"])
    chk("tip within 0.5 mm of Rot(w_r theta) tau(d) + w_r delta on every C row", "max %.2e mm" % tp, tp <= 0.5, "0.5 mm")
    # monotone + per-step limits
    wr = np.array([per[i]["w_r"] for i in iC])
    dC = np.array([per[i]["d_mm"] for i in iC])
    mono = bool(np.all(np.diff(wr) >= -1e-12)) and bool(np.all(np.diff(dC) >= -1e-12))
    chk("w_r monotone (and d)", "min diff w %.2e, d %.2e" % (np.diff(wr).min() if len(wr) > 1 else 0,
                                                          np.diff(dC).min() if len(dC) > 1 else 0), mono, ">= 0")
    t_C = mx(iC, lambda e: e["step"]["tip_mm"])
    a_C = mx(iC, lambda e: e["step"]["axis_deg"])
    chk("C: <= 1.0 mm tip travel per step", "max %.3f mm" % t_C, t_C <= opt["c_step_mm"] + 1e-9, "1.0 mm")
    chk("C: <= 0.8 deg axis per step", "max %.3f deg" % a_C, a_C <= opt["axis_step_deg"] + 1e-9, "0.8 deg")
    t_V = mx(iV, lambda e: e["step"]["tip_mm"])
    chk("V: <= 1 mm tip travel per step", "max %.3f mm" % t_V, t_V <= opt["v_step_mm"] + 1e-9, "1.0 mm")
    t_L = mx(iL, lambda e: max(e["step"]["tip_mm"], e["step"]["corpus_mm"]))
    chk("L: <= 0.5 mm per step (tandem and corpus)", "max %.3f mm" % t_L, t_L <= opt["l_step_mm"] + 1e-9, "0.5 mm")
    wl = np.array([per[i]["w_l"] for i in iL])
    chk("w_l monotone 0 -> 1 in L", "last %.6f" % (wl[-1] if len(wl) else float("nan")),
        bool(len(wl) and np.all(np.diff(wl) >= -1e-12) and abs(wl[-1] - 1.0) < 1e-12), "monotone, ends at 1")
    # end rows
    rc, rl = rows[iC[-1]], rows[iL[-1]]
    tc_F = geo.F_fin - (L - L_C)
    tgt_C = geo.T_C(1.0, L_C)
    Vc = geo.corpus_V

    def corpus_diff(Ta, Tb):
        Ta, Tb = np.asarray(Ta, float), np.asarray(Tb, float)
        return float(np.linalg.norm((Vc @ Ta[:3, :3].T + Ta[:3, 3]) - (Vc @ Tb[:3, :3].T + Tb[:3, 3]), axis=1).max())
    # the pose's own rotation (rounded in pose.json) for the end-of-C corpus target: Rot(theta about p) = R (x - p) + p
    R_pose = geo.T_final[:3, :3]
    tgt_C_pose = geom.rigid4(R_pose, sp["pivot"] - R_pose @ sp["pivot"] + L_C)
    endC = dict(F_mm=float(np.linalg.norm(np.asarray(rc["F"]) - tc_F)), axis_deg=geom.angle_deg(rc["tube_axis"], geo.a_fin),
                x_deg=geom.angle_deg(np.asarray(rc["R_rows"])[0], geo.R_fin_json[0]),
                corpus_mm=corpus_diff(rc["T_corpus"], tgt_C_pose), d_mm=float(rc["d_mm"]), w_r=float(rc["w_r"]))
    endL = dict(F_mm=float(np.linalg.norm(np.asarray(rl["F"]) - geo.F_fin)),
                axis_deg=geom.angle_deg(rl["tube_axis"], geo.a_fin),
                x_deg=geom.angle_deg(np.asarray(rl["R_rows"])[0], geo.R_fin_json[0]),
                corpus_mm=corpus_diff(rl["T_corpus"], geo.T_final))
    okC = endC["F_mm"] <= 0.1 and endC["axis_deg"] <= 0.1 and endC["x_deg"] <= 0.1 and endC["corpus_mm"] <= 0.1 \
        and abs(endC["w_r"] - 1) < 1e-12 and abs(endC["d_mm"] - geo.d_fin) < 1e-9
    okL = endL["F_mm"] <= 0.1 and endL["axis_deg"] <= 0.1 and endL["x_deg"] <= 0.1 and endL["corpus_mm"] <= 0.1
    chk("last C row = tandem at Trans(L_C - L) device_final, corpus Trans(L_C) Rot(theta about p)",
        {k: rnd(v, 4) for k, v in endC.items()}, okC, "0.1 mm / 0.1 deg")
    chk("last L row = device_final and corpus.T_preBT_to_target", {k: rnd(v, 4) for k, v in endL.items()}, okL,
        "0.1 mm / 0.1 deg")
    lc = float(np.linalg.norm(L_C))
    chk("lift in C is 0 unless a flagged fallback is used", "|L_C| %.3f mm (along a_v %.3f)" % (lc, float(L_C @ geo.a_w)),
        True, "0, or flagged")
    # containment
    cV = mn(iV, lambda e: e["contain"]["min_clear_mm"])
    cC = mn(iC, lambda e: e["contain"]["min_clear_mm"])
    nbad = sum(1 for i in iV + iC if not per[i]["contain"]["ok"])
    chk("containment in the %s rest lumen with >= 1 mm clearance on every V and C row" % geo.wall_dir,
        "min clearance V %.2f / C %.2f mm; %d of %d rows below" % (cV, cC, nbad, len(iV) + len(iC)), nbad == 0, "1.0 mm")
    if geo.lum_ref is not None:
        # The plan attaches ">= 1 mm clearance" to the V / C rows (rest lumen) and asks the L rows to be "in the G32
        # final (necked) lumen, used as a proxy": gated = inside (no point outside the closed lumen); the 1 mm
        # clearance is reported beside it.  MEASURED: the last L row IS device_final and the v4 shaft there is ~1.0 mm
        # from G32's necked wall (G32's lumen was pushed open by v3's anterior rods), so ">= 1 mm" would fail the
        # validated final pose itself, which no schedule changes.
        cL = mn(iL, lambda e: e["contain"]["min_clear_mm"])
        noL = sum(1 for i in iL if per[i]["contain"].get("n_outside_lumen", 0) > 0)
        nbL = sum(1 for i in iL if not per[i]["contain"]["ok"])
        chk("containment in the %s lumen (necked proxy) on every L row: inside" % geo.lum_ref["name"],
            "%d of %d rows with a point outside; min clearance %.2f mm (last row = device_final %.2f mm)"
            % (noL, len(iL), cL, per[iL[-1]]["contain"]["min_clear_mm"]), noL == 0, "0 points outside")
        acc.append(dict(test="(reported) L rows with >= 1 mm clearance in the proxy lumen",
                        measured="%d of %d rows below 1 mm; min %.2f mm" % (nbL, len(iL), cL), limit="report",
                        pass_=True, flag=bool(nbL > 0)))
    fr = [(per[i]["d_mm"], per[i]["canal"]["lower"]) for i in iC if per[i]["d_mm"] > opt["d_gate_mm"]]
    frmin = min(f for _, f in fr) if fr else None
    chk("lower_canal_in_tube_frac >= 0.9 on every C row after d = 5 mm", "min %.3f over %d rows" % (frmin, len(fr)),
        frmin is not None and frmin >= opt["frac_min"], "0.9")
    apex_VC = mx(iV + iC, lambda e: abs(e["apex_lift_mm"]))
    chk("apex lift through V and C (reported; expected <= 2 mm)", "max |lift| %.2f mm, end of C %.2f mm" % (
        apex_VC, per[iC[-1]]["apex_lift_mm"]), True, "report")
    # ---- reported
    rep = {}
    s_ios = geo.s_ios
    lead = [(per[i]["d_mm"], per[i]["w_r"] - smoothstep(per[i]["d_mm"] / geo.d_fin)) for i in iC]
    w_ios = max([per[i]["w_r"] for i in iC if per[i]["d_mm"] <= s_ios] or [0.0])
    rep["rotation_lead"] = dict(max_lead=max(v for _, v in lead), d_at_max=[d for d, v in lead if v == max(v for _, v in lead)][0],
                                min_lead=min(v for _, v in lead), w_r_at_internal_os=w_ios, s_internal_os_mm=s_ios,
                                flag_over_half_before_internal_os=bool(w_ios > 0.5),
                                w_r_table=[[round(per[i]["d_mm"], 3), round(per[i]["w_r"], 4)] for i in iC])
    # tandem-alone intrusion into the preBT bladder / rectum at the end-of-C pose (and at device_final for reference)
    intr = {}
    for nm, r in (("end_of_C", rc), ("device_final", rl)):
        Xv, _ = geo.points(r, verts_only=True)
        Xa, _ = geo.points(r)
        intr[nm] = {o: dict(vertices=TM.pen(geo.surf[o], Xv)[0], all_points_max_depth_mm=TM.pen(geo.surf[o], Xa)[0]["max_depth_mm"])
                    for o in ("bladder", "rectum")}
    rep["tandem_alone_intrusion_preBT"] = intr
    # swept envelope of the vaginal tandem per rest station over V and C
    st = geo.lum_rest["st"]
    c, t = st["c"], st["t"]
    half = 0.5 * float(np.median(np.linalg.norm(np.diff(c, axis=0), axis=1)))
    env = [dict(r_max=0.0, ant=-1e9, post=1e9, right=-1e9, left=1e9, r_dir=None, n=0) for _ in range(len(c))]
    for i in iV + iC:
        r = rows[i]
        X, _ = geo.points(r)
        X = X[~geo.in_tissue(X, r["T_corpus"])]
        for k in range(len(c)):
            q = X - c[k]
            ax = q @ t[k]
            m = np.abs(ax) <= half
            if not m.any():
                continue
            qp = q[m] - np.outer(ax[m], t[k])
            ant = geom.ortho([0.0, 1.0, 0.0], t[k])
            rgt = geom.unit(np.cross(ant, t[k]))
            y, x_ = qp @ ant, qp @ rgt
            rr = np.linalg.norm(qp, axis=1)
            j = int(np.argmax(rr))
            E = env[k]
            E["n"] += int(m.sum())
            if rr[j] > E["r_max"]:
                E["r_max"], E["r_dir"], E["row"] = float(rr[j]), [float(x_[j] / rr[j]), float(y[j] / rr[j])], i
            E["ant"], E["post"] = max(E["ant"], float(y.max())), min(E["post"], float(y.min()))
            E["right"], E["left"] = max(E["right"], float(x_.max())), min(E["left"], float(x_.min()))
    rows_env = []
    for k, E in enumerate(env):
        if E["n"] == 0:
            continue
        # anterior share of the swept section: max anterior excursion over (max anterior + max posterior), each
        # clipped at 0 (a station swept only behind its centre has share 0)
        span = max(E["ant"], 0.0) + max(-E["post"], 0.0)
        rows_env.append(dict(station=k, s_mm=float(geo.meta_v["wall"]["s"][k]), r_in_rest_mm=float(st["r"][k]),
                             r_max_mm=rnd(E["r_max"], 2), r_max_dir_right_ant=rnd(E["r_dir"], 3),
                             anterior_max_mm=rnd(E["ant"], 2), posterior_max_mm=rnd(-E["post"], 2),
                             right_max_mm=rnd(E["right"], 2), left_max_mm=rnd(-E["left"], 2),
                             anterior_share=rnd(max(E["ant"], 0.0) / span, 3) if span > 0 else None))
    rep["swept_envelope_per_station"] = dict(
        frame="about each rest station's lumen centre, normal to its tangent; anterior = +y orthogonalised, right = "
              "anterior x tangent; the tandem body (tube + vaginal tandem) outside the cervix/corpus over V and C",
        stations=rows_env)
    # portio bottom vs the wall top at the end of C (rigid carry) and at rest
    top_c, top_t = st["c"][-1], st["t"][-1]
    def portio(Tc):
        Tc = np.asarray(Tc, float)
        Xc = geo.cervix_V @ Tc[:3, :3].T + Tc[:3, 3]
        h = (Xc - top_c) @ top_t
        pc = geo.canal @ Tc[:3, :3].T + Tc[:3, 3]
        near = np.linalg.norm(Xc[:, None, :] - pc[None, :1, :], axis=2)[:, 0] <= 15.0
        return dict(lowest_mm=float(h.min()), lowest_within_15mm_of_os_mm=float(h[near].min()) if near.any() else None,
                    os_mm=float((pc[0] - top_c) @ top_t))
    rep["portio_to_wall_top_gap"] = dict(
        definition="axial coordinate along the wall's top-station tangent, relative to the rest wall's top station "
                   "(positive = above the wall top): the carried cervix's lowest surface point, the lowest within 15 mm "
                   "of the carried O_true, and O_true itself; cervix carried rigidly by the row's corpus transform",
        rest=portio(np.eye(4)), end_of_C=portio(rc["T_corpus"]))
    rep["apex_lift_estimate_mm"] = dict(V_max_abs=mx(iV, lambda e: abs(e["apex_lift_mm"])),
                                        C_max_abs=mx(iC, lambda e: abs(e["apex_lift_mm"])),
                                        end_of_C=per[iC[-1]]["apex_lift_mm"], end_of_L=per[iL[-1]]["apex_lift_mm"])
    # L: tandem and corpus as one body -- the tip and the flange in the corpus's rest frame must not move
    def in_corpus(r):
        Tc = np.asarray(r["T_corpus"], float)
        tip = np.asarray(r["F"], float) + geo.L_iu * geom.unit(r["tube_axis"])
        return np.r_[(tip - Tc[:3, 3]) @ Tc[:3, :3], (np.asarray(r["F"], float) - Tc[:3, 3]) @ Tc[:3, :3]]
    ref_ = in_corpus(rows[iC[-1]])
    rep["L_one_body_max_mm"] = max(float(np.abs(in_corpus(rows[i]) - ref_).max()) for i in iL)
    rep["canal_end_of_C"] = per[iC[-1]]["canal"]
    rep["canal_final"] = per[iL[-1]]["canal"]
    rep["lift_in_C"] = dict(L_C=L_C, norm_mm=lc, along_a_v_mm=float(L_C @ geo.a_w), z_mm=float(L_C[2]),
                            os_rise_along_a_v_in_C_mm=float(L_C @ geo.a_w))
    rep["steps"] = dict(V=len(iV), C=len(iC), L=len(iL),
                        max_corpus_mm_per_step=dict(C=mx(iC, lambda e: e["step"]["corpus_mm"]),
                                                    L=mx(iL, lambda e: e["step"]["corpus_mm"])),
                        max_device_point_mm_per_step=dict(V=mx(iV, lambda e: e["step"]["device_mm"]),
                                                          C=mx(iC, lambda e: e["step"]["device_mm"]),
                                                          L=mx(iL, lambda e: e["step"]["device_mm"])),
                        max_device_point_in_body_mm_per_step=dict(V=mx(iV, lambda e: e["step"]["device_in_body_mm"]),
                                                                  C=mx(iC, lambda e: e["step"]["device_in_body_mm"]),
                                                                  L=mx(iL, lambda e: e["step"]["device_in_body_mm"])),
                        max_axis_deg_per_step=dict(V=mx(iV, lambda e: e["step"]["axis_deg"]),
                                                   C=a_C, L=mx(iL, lambda e: e["step"]["axis_deg"])))
    rep["containment_closed_sheet_S0"] = dict(
        V_min=mn(iV, lambda e: e["contain"].get("min_clear_closed_sheet_mm")),
        C_min=mn(iC, lambda e: e["contain"].get("min_clear_closed_sheet_mm")),
        note="S0 (tf_metrics) clearance to the CLOSED lumen sheet, fan discs included")
    rep["V_tip_to_path_max_mm"] = mx(iV, lambda e: e.get("tip_to_path_mm"))
    summ = dict(accept=acc, pass_all=bool(all(x["pass_"] for x in acc)), reported=rep)
    return dict(summary=summ, per_row=per)


def stub_sofa():
    class _Controller(object):
        def __init__(self, *a, **k):
            pass
    for name in ("Sofa", "Sofa.Core", "Sofa.Simulation", "SofaRuntime"):
        sys.modules.setdefault(name, types.ModuleType(name))
    sys.modules["Sofa"].Core = sys.modules["Sofa.Core"]
    sys.modules["Sofa"].Simulation = sys.modules["Sofa.Simulation"]
    sys.modules["Sofa.Core"].Controller = _Controller
    import vagina_wall

    def _root_readonly(meshes_dir, wall_dir):        # the host must not refresh the scene copies
        return "%s/_scene_%s" % (meshes_dir, wall_dir)
    vagina_wall.scene_mesh_root = _root_readonly
    import scene_hybrid
    return scene_hybrid


def load_run(cfg_path, tag):
    S = stub_sofa()
    cfg = S.load_cfg(cfg_path)
    cfg["tag"] = tag
    inp = S.load_inputs(cfg)
    tgt = S.corpus_target(inp, cfg)
    sched = S.build_schedule(cfg, tgt)
    return S, cfg, inp, tgt, sched


def cmd_gate(a):
    t0 = time.time()
    S, cfg, inp, tgt, sched = load_run(a.cfg, a.tag)
    if cfg.get("insertion_path") != "tandem_first":
        raise SystemExit("gate: cfg insertion_path is %r, not 'tandem_first'" % cfg.get("insertion_path"))
    geo = Geo(cfg["vagina_wall_dir"], cfg["applicator_dir"], a.ref_run)
    rec = tgt["tandem_first"]
    prm = rec["params"]
    rows = [r for r in sched if r["phase"] in ("V", "C", "L")]
    pre = [r for r in sched if r["phase"] not in ("V", "C", "L")]
    g = evaluate_rows(geo, rows, prm)
    s = g["summary"]
    # the device before V (B / P rows) is outside the body: nothing of it above the introitus
    X0, _ = geo.points(pre[-1]) if pre else (np.zeros((0, 3)), None)
    h0 = (X0 - geo.lum_rest["st"]["c"][0]) @ geo.lum_rest["st"]["t"][0] if len(X0) else np.zeros(0)
    s["accept"].append(dict(test="B/P rows: the tandem waits outside the body (no point above the introitus plane)",
                            measured="max height %.2f mm" % (h0.max() if len(h0) else float("nan")),
                            limit="< 0", pass_=bool(len(h0) and h0.max() < 0)))
    s["pass_all"] = bool(all(x["pass_"] for x in s["accept"]))
    # frame_every is run_hybrid's key, deliberately not in scene_hybrid.CFG (G32 carries it too)
    unknown = [k for k in cfg.get("_unknown_keys", []) if k != "frame_every"]
    s["run"] = dict(tag=a.tag, cfg=a.cfg, unknown_cfg_keys=unknown, n_sched=len(sched),
                    phases={p: sum(1 for r in sched if r["phase"] == p) for p in "BPVCL"},
                    max_steps=cfg["max_steps"], rows_plus_settle=len(sched) + int(cfg["max_settle_steps"]),
                    record=dict(version=rec.get("version"), written=rec.get("written"), mode=rec.get("mode"),
                                lift_in_C=rec.get("lift_in_C"), fallback=rec.get("fallback")))
    s["accept"].append(dict(test="schedule fits max_steps (rows + max_settle_steps)",
                            measured="%d + %d = %d" % (len(sched), int(cfg["max_settle_steps"]), s["run"]["rows_plus_settle"]),
                            limit="<= %d" % int(cfg["max_steps"]), pass_=bool(s["run"]["rows_plus_settle"] <= int(cfg["max_steps"]))))
    s["accept"].append(dict(test="cfg keys known to scene_hybrid.CFG", measured=unknown, limit="none unknown",
                            pass_=not unknown))
    s["pass_all"] = bool(all(x["pass_"] for x in s["accept"]))
    out = dict(version=VERSION, written=time.strftime("%Y-%m-%d %H:%M:%S"), tag=a.tag, cfg=a.cfg,
               definitions=__doc__.split("DEFINITIONS")[1].split("Patient-derived")[0].strip(), summary=s,
               per_row=g["per_row"], wall_s=round(time.time() - t0, 1))
    fn = "%s/tf_gate_%s.json" % (LOGS, a.tag)
    json.dump(_jsonable(out), open(fn, "w"), indent=1)
    print_summary(s)
    print("[gate] %s -> %s (%.0f s)" % (a.tag, fn, time.time() - t0), flush=True)


def print_summary(s):
    for x in s["accept"]:
        print("  %-4s %s\n         measured: %s" % ("FLAG" if x.get("flag") else ("PASS" if x["pass_"] else "FAIL"), x["test"],
                                                   json.dumps(_jsonable(x["measured"]))), flush=True)
    rep = s["reported"]
    rl = rep["rotation_lead"]
    print("  reported: rotation lead max %+.3f (d %.1f) min %+.3f; w_r at the internal os (%.1f mm) %.3f, flag %s" % (
        rl["max_lead"], rl["d_at_max"], rl["min_lead"], rl["s_internal_os_mm"], rl["w_r_at_internal_os"],
        rl["flag_over_half_before_internal_os"]))
    for nm, v in rep["tandem_alone_intrusion_preBT"].items():
        print("  reported: tandem-alone intrusion at %s: bladder %d vertices (max %.2f mm), rectum %d (max %.2f mm)" % (
            nm, v["bladder"]["vertices"]["n"], v["bladder"]["vertices"]["max_depth_mm"],
            v["rectum"]["vertices"]["n"], v["rectum"]["vertices"]["max_depth_mm"]))
    pg = rep["portio_to_wall_top_gap"]
    print("  reported: portio bottom vs wall top: rest %s, end of C %s" % (
        {k: rnd(v, 2) for k, v in pg["rest"].items()}, {k: rnd(v, 2) for k, v in pg["end_of_C"].items()}))
    print("  reported: apex lift estimate %s" % {k: rnd(v, 2) for k, v in rep["apex_lift_estimate_mm"].items()})
    env = rep["swept_envelope_per_station"]["stations"]
    print("  reported: swept envelope (station s: r_max / r_in, anterior max, posterior max, anterior share):")
    for e in env[::4] + ([env[-1]] if env else []):
        print("     st %2d s %6.1f  r_max %5.1f / r_in %5.1f  ant %5.1f  post %5.1f  share %s" % (
            e["station"], e["s_mm"], e["r_max_mm"], e["r_in_rest_mm"], e["anterior_max_mm"], e["posterior_max_mm"],
            e["anterior_share"]))
    print("  PASS_ALL %s" % s["pass_all"], flush=True)


# ============================================================================================ fake-SOFA replay
class _D(object):
    def __init__(self, v):
        self.value = v

    def getValueString(self):
        return str(self.value)


class _Obj(object):
    def __init__(self, typ, kw):
        self._typ = typ
        for k, v in kw.items():
            setattr(self, k, _D(v))

    def findData(self, k):
        return getattr(self, k, None)


class _Node(object):
    def __init__(self, path, log):
        self._path, self._log, self._items = path, log, []

    def addChild(self, name):
        c = _Node(self._path + "/" + name, self._log)
        setattr(self, name, c)
        self._items.append(c)
        self._log.append(("child", c._path))
        return c

    def addObject(self, typ, name=None, **kw):
        o = _Obj(typ, kw)
        if name:
            setattr(self, name, o)
        self._items.append(o)
        self._log.append(("obj", self._path, typ, name))
        return o


def cmd_replay(a):
    """Build the whole scene on a fake SOFA API and step the controller through every row (see the module doc)."""
    t0 = time.time()
    S = stub_sofa()
    cfg = S.load_cfg(a.cfg)
    cfg["tag"] = a.tag
    cfg["min_vol_ratio_abort"] = -1e9                   # the fake tets have no meaningful volume
    log = []
    root = _Node("", log)
    inp = S.load_inputs(cfg)
    ctx = S.build_scene(root, cfg, inp)
    # every body the controller solves or reads: the five DEFORMABLE ones (static obstacles included, as before) plus
    # ctx["deformable"]'s extras -- the elastic corpus of corpus_model "fem", whose topology post_init reads (review
    # LOW-6: stubbing S.DEFORMABLE alone raised AttributeError in post_init on every fem cfg)
    bodies = list(S.DEFORMABLE) + [b for b in ctx.get("deformable", []) if b not in S.DEFORMABLE]
    for b in bodies:
        nd = ctx["nodes"][b]
        nd.dofs.position = _D(ctx["X0"][b].tolist())
        nd.dofs.velocity = _D(np.zeros_like(ctx["X0"][b]).tolist())
        nd.topo.tetrahedra = _D([[0, 1, 2, 3]])
    root.gcs.currentNumConstraints = _D(300)
    root.gcs.currentError = _D(0.5)
    root.gcs.currentIterations = _D(40)
    root.gcs.constraintForces = _D([0.1])
    ctrl = S.HybridController(name="h", ctx=ctx, out_dir=None)
    S.post_init(ctx)
    summ = S.scene_summary(ctx)
    sched = ctx["sched"]
    n_max = min(int(cfg["max_steps"]), len(sched) + 5)
    while not ctrl.done and ctrl.k < n_max:
        r = sched[min(ctrl.k, len(sched) - 1)]
        Tc = np.asarray(r["T_corpus"], float)
        for b in bodies:                                # the cervix (and an elastic corpus) carried by the row's pose
            X0 = ctx["X0"][b]
            X = X0 @ Tc[:3, :3].T + Tc[:3, 3] if b in ("cervix", "corpus") else X0.copy()
            ctx["nodes"][b].dofs.position.value = X.tolist()
        ctrl._begin()
        ctrl._end()
    rows = ctrl.rows
    # depth engagement: each node engages at the first step whose row carries tip_s >= canal_s, never before
    cs = ctx.get("canal_s")
    eng = ctrl.eng_step
    lag = []
    if cs is not None:
        for i, s_i in enumerate(cs):
            first = next((k for k, r in enumerate(sched) if r["phase"] not in ("B", "P") and r.get("tip_s") is not None
                          and float(r["tip_s"]) >= float(s_i)), None)
            lag.append(None if (first is None or eng[i] < 0) else int(eng[i]) - first)
    ph_of = lambda k: sched[min(k, len(sched) - 1)]["phase"]  # noqa: E731
    n_eng = [r.get("canal_tie", {}).get("n_engaged") for r in rows]
    out = dict(tag=a.tag, graph_ops=len(log), ovoid_nodes=[x for x in log if x[0] == "child" and "ovoid" in x[1]],
               ctx_ovoids_is_none=ctx.get("ovoids") is None, n_steps=len(rows), status=ctrl.status,
               phases_logged={p: sum(1 for r in rows if r["phase"] == p) for p in "BPVCLH"},
               scene_summary_phases=summ.get("phases"), extra_tandem_first=summ.get("tandem_first"),
               ovoid_body=summ.get("ovoid_body"), tie_set=summ.get("canal_tie_cfg"),
               ties=dict(n_nodes=int(len(eng)), n_engaged=int((eng >= 0).sum()),
                         engage_lag_steps=dict(min=min([x for x in lag if x is not None], default=None),
                                               max=max([x for x in lag if x is not None], default=None),
                                               n_never=int(sum(1 for x in lag if x is None))),
                         first_engaged_step=int(eng[eng >= 0].min()) if (eng >= 0).any() else None,
                         first_engaged_phase=ph_of(int(eng[eng >= 0].min())) if (eng >= 0).any() else None,
                         last_engaged_step=int(eng.max()) if (eng >= 0).any() else None,
                         plateau_from_step=next((k for k, n in enumerate(n_eng) if n == max(x for x in n_eng if x is not None)), None),
                         n_engaged_in_V=int(sum(1 for k in eng if k >= 0 and ph_of(int(k)) == "V"))),
               apex_lift_logged=dict(end_of_C=next((r["apex_lift_mm"] for r in reversed(rows) if r["phase"] == "C"), None),
                                     last=rows[-1].get("apex_lift_mm") if rows else None),
               tf_logged_last=rows[-1].get("tf") if rows else None, wall_s=round(time.time() - t0, 1))
    ok = (out["ctx_ovoids_is_none"] and not out["ovoid_nodes"] and out["ties"]["n_engaged"] == out["ties"]["n_nodes"]
          and out["ties"]["engage_lag_steps"]["max"] is not None and out["ties"]["engage_lag_steps"]["max"] <= 0
          and out["ties"]["engage_lag_steps"]["min"] >= 0 and all("tf" in r for r in rows if r["phase"] in "VCLH"))
    out["pass"] = bool(ok)
    fn = "%s/tf_gate_replay_%s.json" % (LOGS, a.tag)
    json.dump(_jsonable(out), open(fn, "w"), indent=1, default=str)
    print(json.dumps(_jsonable({k: v for k, v in out.items() if k != "ovoid_nodes"}), default=str, indent=1))
    print("[replay] %s: %s -> %s" % (a.tag, "PASS" if ok else "FAIL", fn), flush=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["search", "write", "gate", "replay"])
    ap.add_argument("--wall", default=OPT["wall"])
    ap.add_argument("--app", default=OPT["app"])
    ap.add_argument("--ref-run", default=OPT["ref_run"], help="run whose final wall is the L-phase proxy lumen (G32)")
    ap.add_argument("--write", action="store_true", help="search: write the chosen schedule into <app>/pose.json")
    ap.add_argument("--force", action="store_true", help="write: store the schedule even if the full gate fails")
    ap.add_argument("--cfg", default=None, help="gate / replay: the run cfg (runs/_cfg/<TAG>.json)")
    ap.add_argument("--tag", default="TF0")
    a = ap.parse_args()
    if a.cmd == "search":
        cmd_search(a)
    elif a.cmd == "write":
        write_chosen(Geo(a.wall, a.app, a.ref_run), json.load(open(LOGS + "/tf_gate_search.json")), a)
    elif a.cfg is None:
        raise SystemExit("%s needs --cfg" % a.cmd)
    elif a.cmd == "gate":
        cmd_gate(a)
    else:
        cmd_replay(a)


if __name__ == "__main__":
    main()
